### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: query

### ISSUE THREAD

**Issue by cblaze22** [danielcrenna/tweetsharp#172]
I am getting this error for a user below.  I can't reproduce it.

System.ArgumentNullException: Value cannot be null. Parameter name: query
`System.ArgumentNullException: Value cannot be null.
Parameter name: query
   at System.Compat.Web.HttpUtility.ParseQueryString(String query, Encoding encoding) in f:\src\hammock\src\net40\Hammock\Mono\HttpUtility.cs:line 1220
   at System.Compat.Web.HttpUtility.ParseQueryString(String query) in f:\src\hammock\src\net40\Hammock\Mono\HttpUtility.cs:line 1214
   at TweetSharp.TwitterService.GetRequestToken(String callback) in f:\My Webs\BasketballTournaments\MainBranchRevert\Projects\tweetsharp-master\src\TweetSharp\TwitterService.OAuth.cs:line 200`

**Comment by Yortw** [comment]
It seems this is in the mono build which I am not in a position to build/test. Does it work on a more common .Net runtime? My best guess is the outgoing query string is null, but I don't know why that would be. Did you pass a null callback maybe?
Alternatively are you able to debug the code and find out why null is being passed to ParseQueryString?

**Comment by BHEADRICK** [comment]
I'm also getting this error, and my environment is Windows Server / IIS

**Comment by Yortw** [comment]
Can you try one of the alternate TweetSharp packages? Maybe TweetSharp-Unofficial or TweetMoaSharp? They should be drop in replacements.
